# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be included in the set of available tasks.

ENV["RAILS_ENV"] = "test"

require_relative "test/dummy/config/application"

Rails.application.load_tasks
